### ISSUE TITLE
ImportError with muutils 0.9.1; downgrading fails on Python 3.14

### ISSUE THREAD

**Issue by Finnk11** [understanding-search/maze-dataset#82]
## Description

Importing `maze_dataset` fails with `muutils==0.9.1` because it imports `_FORMAT_KEY` from `muutils.json_serialize.util`. The constant now lives in `muutils.json_serialize.types`.

Downgrading to `muutils==0.8.10` resolves that missing constant but causes a separate compatibility error with Python 3.14.

## Environment

- OS: Ubuntu under WSL
- Python: 3.14.7
- Environment manager: Conda; packages installed using pip
- maze-dataset: 1.4.2
- muutils: 0.9.1
- zanj: 0.6.0

## Minimal reproduction

```python
from maze_dataset.generation import LatticeMazeGenerators
```

## Expected behavior

The import succeeds without modifying dependency internals.

## Actual behavior

With `muutils==0.9.1`:

```text
  File "maze_dataset/dataset/collected_dataset.py", line 20, in <module>
    from muutils.json_serialize.util import _FORMAT_KEY, JSONdict
ImportError: cannot import name '_FORMAT_KEY' from 'muutils.json_serialize.util'
```

## Attempted dependency downgrade

With `muutils==0.8.10`, the import instead fails with:

```text
  File "maze_dataset/maze/lattice_maze.py", line 162, in LatticeMaze
    generation_meta: dict | None = serializable_field(default=None, compare=False)

  File "muutils/json_serialize/serializable_field.py", line 93, in __init__
    super().__init__(**super_kwargs)

TypeError: Field.__init__() missing 1 required positional argument: 'doc'
```

This version therefore does not provide a working downgrade on Python 3.14.

## Temporary workaround

The following shim before importing `maze_dataset` allows maze generation to work with `muutils==0.9.1`:

```python
import muutils.json_serialize.util as serialization_util

if not hasattr(serialization_util, "_FORMAT_KEY"):
    from muutils.json_serialize.types import _FORMAT_KEY

    serialization_util._FORMAT_KEY = _FORMAT_KEY

from maze_dataset.generation import LatticeMazeGenerators
```

Could the imports and dependency constraints be updated to support a compatible combination without this workaround?
---
This issue was drafted with OpenAI Codex using error logs and dependency checks from my environment. I manually reviewed it before submitting.
